./exportMooreaBiocode.sh "Cairns LAB" "CAIRNS_LEGACY"
./exportMooreaBiocode.sh "CMPI" "MORITZ_LEGACY"
./exportMooreaBiocode.sh "Harasewych LAB" "HARASEWYCH_LEGACY"
./exportMooreaBiocode.sh "INDIAN RIVER LAGOON" "IRLA_ARMS_Dec_2009"
./exportMooreaBiocode.sh "INDIAN RIVER LAGOON" "IRLA_ARMS_June_2009"
./exportMooreaBiocode.sh "Lemaitre LAB" "LEMAITRE_LEGACY"
./exportMooreaBiocode.sh "MEYER ARMS" "BIOMAR_2017"
./exportMooreaBiocode.sh "MEYER ARMS" "CRIOBE_2018"
./exportMooreaBiocode.sh "MEYER ARMS" "FLORIDA_KEYS_2017"
./exportMooreaBiocode.sh "MEYER ARMS" "MOOREA_TETIAROA_2018"
./exportMooreaBiocode.sh "MEYER ARMS" "TETIAROA_2014"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "FSUML_2013"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "CARRIE_BOW_2012"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "CARRIE_BOW_2014"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "GENESEE_2015"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "MADAGASCAR_2016"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "NATURE_BRIDGE_Bay_Area_2013"
./exportMooreaBiocode.sh "MEYER BIOCUBE" "SOLOMONS_2014"
./exportMooreaBiocode.sh "MEYER LAB" "COWRIES"
./exportMooreaBiocode.sh "MEYER LAB" "MALDIVES_2018"
./exportMooreaBiocode.sh "MEYER LAB" "NATURE_BRIDGE_Bay_Area_2013"
./exportMooreaBiocode.sh "MEYER LAB" "TETIAROA_2014"
./exportMooreaBiocode.sh "MEYER LAB" "TITUS_MALDIVES"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "ALGAE_LEGACY"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "FUNGI_LEGACY"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MARbol"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_2006"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_BMOO"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_HANSON"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_LIITTSCHWAGER"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_OUTREACH"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_PARASITE"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_PLANKTON"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_REU"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_Spring_2008"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_Spring_2010"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_TEMP"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_Turbinaria_2011"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MINV_Turbinaria_2012"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MVERT_FISHES"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MVERT_FLMOO"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MVERT_GASPAR"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MVERT_MARQ"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "MVERT_MOOP"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "OUTREACH"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "PLANT_BRYO"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "PLANT_FERN"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "PLANT_LEGACY"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "PLANTS_SPOTSWOOD"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "SYMBIOCODE"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "TINV_LEGACY"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "TINV_LIITTSCHWAGER"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "TINV_MOLLUSCA"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "TVERT_LEGACY"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "TVERT_RATS"
./exportMooreaBiocode.sh "MOOREA BIOCODE" "TVERT_SPOTSWOOD"
./exportMooreaBiocode.sh "Norenburg LAB" "NORENBURG_LEGACY"
./exportMooreaBiocode.sh "Osborn LAB" "OSBORN_LEGACY"
./exportMooreaBiocode.sh "PEER DEADHEADS" "PEER_2016"
./exportMooreaBiocode.sh "Phillips LAB" "PHILLIPS_LEGACY"
./exportMooreaBiocode.sh "PIRE ARMS" "ANILAO_2015"
./exportMooreaBiocode.sh "PIRE ARMS" "INDO_PIRE"
./exportMooreaBiocode.sh "PIRE ARMS" "NOAA_Sponges"
./exportMooreaBiocode.sh "PIRE ARMS" "TIMOR_2014"
./exportMooreaBiocode.sh "SIBARCODE" "SIBARCODE_LEGACY"
./exportMooreaBiocode.sh "SMITHSONIAN BOEM PROJECT" "BOEM_2018_OIMB"
./exportMooreaBiocode.sh "SMITHSONIAN BOEM PROJECT" "Dutch_Harbor_2018"
./exportMooreaBiocode.sh "SMITHSONIAN BOEM PROJECT" "WAML_DISCO_2018"
./exportMooreaBiocode.sh "SMITHSONIAN DROP PROJECT" "DROP2013"
./exportMooreaBiocode.sh "SMITHSONIAN DROP PROJECT" "DROP2015"
./exportMooreaBiocode.sh "SMITHSONIAN DROP PROJECT" "DROP2016"
./exportMooreaBiocode.sh "SMITHSONIAN DROP PROJECT" "DROP2017"
./exportMooreaBiocode.sh "Strong LAB" "STRONG_LEGACY"
./exportMooreaBiocode.sh "USAID INDO" "ACEH_2012"
./exportMooreaBiocode.sh "USAID INDO" "BALI_2010"
./exportMooreaBiocode.sh "USAID INDO" "BALI_2011"
./exportMooreaBiocode.sh "USAID INDO" "BALI_2012"
./exportMooreaBiocode.sh "USAID INDO" "BALI_2013"
./exportMooreaBiocode.sh "USAID INDO" "IBRC_LIMPET"
./exportMooreaBiocode.sh "USAID INDO" "MCKEON_2011"
./exportMooreaBiocode.sh "USAID INDO" "MYANMAR_2014"
./exportMooreaBiocode.sh "USAID INDO" "SERIBU_2012"
./exportMooreaBiocode.sh "USAID INDO" "SERIBU_2014"
./exportMooreaBiocode.sh "WINDSOR LAB" "WINDSOR_LEGACY"
